import type { PortalData } from '../types'
import { plainTextToHtml } from './html'

/** شناسه‌های پایدار برای لینک‌پذیری و تست UI */
export const DEMO_CLIENT_ID = 'client_ali_rezaei'
export const DEMO_LAWYER_KARIMI = 'lawyer_maryam_karimi'
export const DEMO_LAWYER_HOSSEINI = 'lawyer_amir_hosseini'

const CASE_KHAL = 'case_khal_yed'
const CASE_TALAGH = 'case_talagh'
const CASE_PEYMAN = 'case_peyman'
const CASE_KALAH = 'case_kolah'

/**
 * دادهٔ نمونه فقط وقتی storage خالی است استفاده می‌شود.
 * هرگز روی دادهٔ موجود کاربر بازنویسی نمی‌کند.
 */
export function buildDemoPortalData(): PortalData {
  const now = Date.now()
  const iso = (offsetDays: number, hour = 10, minute = 0) => {
    const d = new Date(now + offsetDays * 24 * 60 * 60 * 1000)
    d.setHours(hour, minute, 0, 0)
    return d.toISOString()
  }

  const desc = (text: string) => ({
    description: text,
    descriptionHtml: plainTextToHtml(text),
  })

  return {
    profile: {
      id: DEMO_CLIENT_ID,
      name: 'علی رضایی',
      phone: '09123456789',
      email: 'ali.rezaei@example.com',
    },
    lawyers: [
      {
        id: DEMO_LAWYER_KARIMI,
        name: 'دکتر مریم کریمی',
        title: 'وکیل پایه یک دادگستری',
        specialty: 'حقوق مدنی و ملکی',
        phone: '02188771234',
        email: 'm.karimi@vokala.example.com',
        barNumber: '۱۴۰۲/۸۸۴۱',
      },
      {
        id: DEMO_LAWYER_HOSSEINI,
        name: 'امیرحسین حسینی',
        title: 'وکیل پایه یک دادگستری',
        specialty: 'حقوق خانواده و کیفری',
        phone: '02166554433',
        email: 'a.hosseini@vokala.example.com',
        barNumber: '۱۳۹۸/۳۲۰۱',
      },
    ],
    cases: [
      {
        id: CASE_KHAL,
        caseNumber: '۱۴۰۴-۰۰۱۲۸',
        title: 'دعوای خلع ید ملک مسکونی',
        ...desc(
          'مطالبه خلع ید از ملک مسکونی واقع در منطقه ۳ تهران. مدارک مالکیت و گزارش کارشناسی تکمیل شده و پرونده در مرحله پیگیری دادگاه است.'
        ),
        legalArea: 'civil',
        status: 'active',
        lawyerId: DEMO_LAWYER_KARIMI,
        createdBy: 'lawyer',
        lawyerSynced: true,
        comments: [
          {
            id: 'cmt_khal_1',
            authorRole: 'lawyer',
            authorName: 'دکتر مریم کریمی',
            bodyHtml:
              '<p>مدارک مالکیت بررسی شد. لطفاً در صورت امکان <strong>قبض آب و برق</strong> سال جاری را هم بارگذاری کنید.</p>',
            attachments: [],
            createdAt: iso(-20, 14, 0),
          },
          {
            id: 'cmt_khal_2',
            authorRole: 'client',
            authorName: 'علی رضایی',
            bodyHtml:
              '<p>حتماً؛ فردا قبض‌ها را اسکن و ارسال می‌کنم.</p>',
            attachments: [],
            createdAt: iso(-19, 9, 30),
          },
        ],
        documents: [
          {
            id: 'doc_sanad',
            name: 'سند-مالکیت.pdf',
            mimeType: 'application/pdf',
            size: 245_000,
            uploadedAt: iso(-25),
            status: 'available',
          },
          {
            id: 'doc_karshenas',
            name: 'گزارش-کارشناسی.pdf',
            mimeType: 'application/pdf',
            size: 512_000,
            uploadedAt: iso(-12),
            status: 'available',
          },
          {
            id: 'doc_shenasname',
            name: 'تصویر-شناسنامه.jpg',
            mimeType: 'image/jpeg',
            size: 180_000,
            uploadedAt: iso(-24),
            status: 'available',
          },
        ],
        timeline: [
          {
            id: 'tl_k1',
            type: 'created',
            title: 'ایجاد پرونده',
            description: 'پرونده توسط وکیل مسئول ثبت شد.',
            occurredAt: iso(-30),
          },
          {
            id: 'tl_k2',
            type: 'review',
            title: 'بررسی توسط وکیل',
            description: 'مدارک اولیه بررسی و نواقص اعلام شد.',
            occurredAt: iso(-28),
          },
          {
            id: 'tl_k3',
            type: 'document',
            title: 'ارسال مدارک',
            description: 'سند مالکیت و شناسنامه بارگذاری شد.',
            occurredAt: iso(-25),
          },
          {
            id: 'tl_k4',
            type: 'session',
            title: 'جلسه مشاوره',
            description: 'مشاوره حضوری درباره استراتژی دعوا برگزار شد.',
            occurredAt: iso(-18),
          },
          {
            id: 'tl_k5',
            type: 'status',
            title: 'بروزرسانی وضعیت',
            description: 'وضعیت پرونده به «فعال» تغییر کرد.',
            occurredAt: iso(-15),
          },
          {
            id: 'tl_k6',
            type: 'payment',
            title: 'پرداخت پیش‌پرداخت',
            description: 'مبلغ ۴۰ میلیون ریال به‌عنوان پیش‌پرداخت ثبت شد.',
            occurredAt: iso(-14),
          },
        ],
        createdAt: iso(-30),
        updatedAt: iso(-2),
      },
      {
        id: CASE_TALAGH,
        caseNumber: '۱۴۰۴-۰۰۲۰۱',
        title: 'پرونده طلاق توافقی',
        ...desc(
          'درخواست طلاق توافقی. جلسات مشاوره خانواده در جریان است و مدارک تکمیلی در انتظار بررسی وکیل است.'
        ),
        legalArea: 'family',
        status: 'under_review',
        lawyerId: DEMO_LAWYER_HOSSEINI,
        createdBy: 'lawyer',
        lawyerSynced: true,
        comments: [
          {
            id: 'cmt_talagh_1',
            authorRole: 'lawyer',
            authorName: 'امیرحسین حسینی',
            bodyHtml:
              '<p>فرم درخواست دریافت شد. یک جلسه مشاوره دیگر برای تکمیل توافقات لازم است.</p>',
            attachments: [],
            createdAt: iso(-5, 11, 0),
          },
        ],
        documents: [
          {
            id: 'doc_aghd',
            name: 'سند-ازدواج.pdf',
            mimeType: 'application/pdf',
            size: 320_000,
            uploadedAt: iso(-10),
            status: 'available',
          },
          {
            id: 'doc_form',
            name: 'فرم-درخواست.docx',
            mimeType:
              'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
            size: 64_000,
            uploadedAt: iso(-8),
            status: 'processing',
          },
        ],
        timeline: [
          {
            id: 'tl_t1',
            type: 'created',
            title: 'ایجاد پرونده',
            occurredAt: iso(-12),
          },
          {
            id: 'tl_t2',
            type: 'document',
            title: 'ارسال مدارک',
            description: 'سند ازدواج بارگذاری شد.',
            occurredAt: iso(-10),
          },
          {
            id: 'tl_t3',
            type: 'review',
            title: 'در انتظار بررسی وکیل',
            description: 'وکیل در حال بررسی مدارک تکمیلی است.',
            occurredAt: iso(-3),
          },
        ],
        createdAt: iso(-12),
        updatedAt: iso(-1),
      },
      {
        id: CASE_PEYMAN,
        caseNumber: '۱۴۰۳-۰۱۱۸',
        title: 'اختلاف قرارداد پیمانکاری',
        ...desc(
          'مطالبه وجه قرارداد و خسارت تأخیر تأدیه. رأی نهایی صادر و پرونده مختومه شده است.'
        ),
        legalArea: 'commercial',
        status: 'closed',
        lawyerId: DEMO_LAWYER_KARIMI,
        createdBy: 'lawyer',
        lawyerSynced: true,
        comments: [],
        documents: [
          {
            id: 'doc_contract',
            name: 'قرارداد-پیمانکاری.pdf',
            mimeType: 'application/pdf',
            size: 890_000,
            uploadedAt: iso(-95),
            status: 'available',
          },
          {
            id: 'doc_ray',
            name: 'رأی-نهایی.pdf',
            mimeType: 'application/pdf',
            size: 156_000,
            uploadedAt: iso(-20),
            status: 'available',
          },
        ],
        timeline: [
          {
            id: 'tl_p1',
            type: 'created',
            title: 'ایجاد پرونده',
            occurredAt: iso(-100),
          },
          {
            id: 'tl_p2',
            type: 'session',
            title: 'جلسه دادگاه',
            description: 'اولین جلسه رسیدگی برگزار شد.',
            occurredAt: iso(-60),
          },
          {
            id: 'tl_p3',
            type: 'status',
            title: 'صدور رأی',
            description: 'رأی به نفع موکل صادر شد.',
            occurredAt: iso(-22),
          },
          {
            id: 'tl_p4',
            type: 'status',
            title: 'مختومه شدن پرونده',
            occurredAt: iso(-18),
          },
        ],
        createdAt: iso(-100),
        updatedAt: iso(-18),
      },
      {
        id: CASE_KALAH,
        caseNumber: '۱۴۰۴-۰۰۰۴۵',
        title: 'شکایت کلاهبرداری رایانه‌ای',
        ...desc(
          'پرونده به درخواست موکل لغو شد؛ پیگیری از طریق مرجع دیگری انجام می‌شود.'
        ),
        legalArea: 'criminal',
        status: 'cancelled',
        lawyerId: DEMO_LAWYER_HOSSEINI,
        createdBy: 'lawyer',
        lawyerSynced: true,
        comments: [],
        documents: [],
        timeline: [
          {
            id: 'tl_c1',
            type: 'created',
            title: 'ایجاد پرونده',
            occurredAt: iso(-40),
          },
          {
            id: 'tl_c2',
            type: 'note',
            title: 'درخواست لغو',
            description: 'موکل درخواست توقف پیگیری را اعلام کرد.',
            occurredAt: iso(-35),
          },
          {
            id: 'tl_c3',
            type: 'status',
            title: 'لغو پرونده',
            occurredAt: iso(-34),
          },
        ],
        createdAt: iso(-40),
        updatedAt: iso(-34),
      },
    ],
    sessions: [
      {
        id: 'session_consult_upcoming',
        title: 'مشاوره پیگیری خلع ید',
        type: 'consultation',
        status: 'confirmed',
        caseId: CASE_KHAL,
        lawyerId: DEMO_LAWYER_KARIMI,
        startsAt: iso(3, 11, 30),
        durationMinutes: 45,
        location: 'دفتر وکالت — خیابان ولیعصر',
        description:
          'بررسی آخرین گزارش کارشناسی و آمادگی برای جلسه دادگاه.',
        canCancel: true,
        canReschedule: true,
        createdAt: iso(-5),
        updatedAt: iso(-1),
      },
      {
        id: 'session_online_upcoming',
        title: 'جلسه آنلاین مشاوره خانواده',
        type: 'online',
        status: 'scheduled',
        caseId: CASE_TALAGH,
        lawyerId: DEMO_LAWYER_HOSSEINI,
        startsAt: iso(7, 16, 0),
        durationMinutes: 30,
        meetingUrl: 'https://meet.vokala.example.com/room/talagh-01',
        description: 'مرور مدارک و هماهنگی مراحل بعدی طلاق توافقی.',
        canCancel: true,
        canReschedule: true,
        createdAt: iso(-4),
        updatedAt: iso(-4),
      },
      {
        id: 'session_court_upcoming',
        title: 'جلسه دادگاه شعبه ۸ حقوقی',
        type: 'court',
        status: 'confirmed',
        caseId: CASE_KHAL,
        lawyerId: DEMO_LAWYER_KARIMI,
        startsAt: iso(14, 9, 0),
        durationMinutes: 90,
        location: 'دادگاه عمومی حقوقی تهران — شعبه ۸',
        description: 'اولین جلسه رسیدگی به دعوای خلع ید.',
        canCancel: false,
        canReschedule: false,
        createdAt: iso(-10),
        updatedAt: iso(-2),
      },
      {
        id: 'session_past_consult',
        title: 'مشاوره اولیه خلع ید',
        type: 'in_person',
        status: 'completed',
        caseId: CASE_KHAL,
        lawyerId: DEMO_LAWYER_KARIMI,
        startsAt: iso(-18, 10, 0),
        durationMinutes: 60,
        location: 'دفتر وکالت — خیابان ولیعصر',
        description: 'تبیین استراتژی دعوا و فهرست مدارک مورد نیاز.',
        canCancel: false,
        canReschedule: false,
        createdAt: iso(-25),
        updatedAt: iso(-18),
      },
      {
        id: 'session_past_court',
        title: 'جلسه رسیدگی قرارداد پیمانکاری',
        type: 'court',
        status: 'completed',
        caseId: CASE_PEYMAN,
        lawyerId: DEMO_LAWYER_KARIMI,
        startsAt: iso(-60, 9, 30),
        durationMinutes: 120,
        location: 'دادگاه عمومی حقوقی تهران — شعبه ۱۲',
        canCancel: false,
        canReschedule: false,
        createdAt: iso(-70),
        updatedAt: iso(-60),
      },
      {
        id: 'session_cancelled',
        title: 'پیگیری تلفنی پرونده کیفری',
        type: 'follow_up',
        status: 'cancelled',
        caseId: CASE_KALAH,
        lawyerId: DEMO_LAWYER_HOSSEINI,
        startsAt: iso(-32, 15, 0),
        durationMinutes: 20,
        description: 'جلسه به درخواست موکل لغو شد.',
        canCancel: false,
        canReschedule: false,
        createdAt: iso(-38),
        updatedAt: iso(-33),
      },
      {
        id: 'session_no_show',
        title: 'مشاوره تکمیلی خانواده',
        type: 'consultation',
        status: 'no_show',
        caseId: CASE_TALAGH,
        lawyerId: DEMO_LAWYER_HOSSEINI,
        startsAt: iso(-6, 17, 0),
        durationMinutes: 30,
        location: 'دفتر وکالت — سعادت‌آباد',
        description: 'موکل در جلسه حاضر نشد.',
        canCancel: false,
        canReschedule: true,
        createdAt: iso(-9),
        updatedAt: iso(-6),
      },
    ],
    payments: [
      {
        id: 'pay_prepayment',
        title: 'پیش‌پرداخت حق‌الوکاله — خلع ید',
        caseId: CASE_KHAL,
        amount: 40_000_000,
        status: 'completed',
        method: 'transfer',
        transactionId: 'TRX-1404-88421',
        paidAt: iso(-14, 12, 20),
        description: 'پیش‌پرداخت مرحله بدوی طبق قرارداد.',
        createdAt: iso(-14),
        updatedAt: iso(-14),
      },
      {
        id: 'pay_installment',
        title: 'قسط دوم حق‌الوکاله — خلع ید',
        caseId: CASE_KHAL,
        amount: 40_000_000,
        status: 'pending',
        method: 'online',
        description: 'سررسید قسط دوم طبق توافق.',
        paidAt: null,
        createdAt: iso(-3),
        updatedAt: iso(-3),
      },
      {
        id: 'pay_consult',
        title: 'هزینه جلسه مشاوره خانواده',
        caseId: CASE_TALAGH,
        amount: 8_500_000,
        status: 'failed',
        method: 'online',
        transactionId: 'TRX-1404-90112',
        paidAt: null,
        description: 'پرداخت از درگاه ناموفق بود. می‌توانید مجدداً تلاش کنید.',
        createdAt: iso(-2),
        updatedAt: iso(-2),
      },
      {
        id: 'pay_peyman_full',
        title: 'تسویه نهایی — قرارداد پیمانکاری',
        caseId: CASE_PEYMAN,
        amount: 100_000_000,
        status: 'completed',
        method: 'cheque',
        transactionId: 'CHQ-1403-5510',
        paidAt: iso(-40, 11, 0),
        description: 'تسویه باقیمانده حق‌الوکاله پس از صدور رأی.',
        createdAt: iso(-40),
        updatedAt: iso(-40),
      },
      {
        id: 'pay_refund',
        title: 'بازگشت وجه — پرونده کیفری',
        caseId: CASE_KALAH,
        amount: 15_000_000,
        status: 'refunded',
        method: 'transfer',
        transactionId: 'TRX-1404-77201',
        paidAt: iso(-33, 14, 0),
        description: 'بازگشت پیش‌پرداخت پس از لغو پرونده.',
        createdAt: iso(-33),
        updatedAt: iso(-33),
      },
      {
        id: 'pay_cancelled',
        title: 'پرداخت هزینه کارشناسی',
        caseId: CASE_KHAL,
        amount: 8_000_000,
        status: 'cancelled',
        method: 'online',
        paidAt: null,
        description: 'درخواست پرداخت پیش از تأیید لغو شد.',
        createdAt: iso(-20),
        updatedAt: iso(-19),
      },
    ],
  }
}
